version: 2.1
orbs:
  golang-ci: financial-times/golang-ci@1.0.0

workflows:
  version: 2.1
  tests_and_docker:
    jobs:
      - golang-ci/build-and-test:
          name: build-and-test-project
          working-dir: ./cmd/republisher

      - golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project

  scanning:
    jobs:
      - golang-ci/scan:
          name: scan-dependencies
          context: org-global
