version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@1

jobs:
  build-and-publish-docker-image:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag coco/publish-failure-resolver-go:latest .
      - run:
          name: Login in Dockerhub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - deploy:
          name: Push Docker image
          command: docker push coco/publish-failure-resolver-go:latest

workflows:
  tests_and_docker:
    jobs:
      - ft-golang-ci/build-and-test:
          name: build-and-test-project
      - build-and-publish-docker-image:
          name: build-and-publish-docker-image
          requires:
            - build-and-test-project
          filters:
            branches:
              only: "master"

  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context: cm-team-snyk
